### ISSUE TITLE
Day 2- Login and Registration(Shanmathy JS)

### ISSUE THREAD

**Issue by Shaikhanis7** [Shaikhanis7/Job-searching-Portal#9]

**Comment by Shanmathy1** [comment]
[Login.txt](https://github.com/user-attachments/files/16493673/Login.txt)

**Comment by Shanmathy1** [comment]
Done

**Comment by Shanmathy1** [comment]
[Register.txt](https://github.com/user-attachments/files/16493684/Register.txt)

**Comment by Shanmathy1** [comment]
Done
